name: flutter_email_contact
description: "A flutter package to let your users send you feedback emails."
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.6.2
  flutter:
    sdk: flutter
  flutter_fit_utils: ^2.4.3
  flutter_fit_utils_config: ^1.0.2
  flutter_fit_utils_ui: ^1.6.0
  flutter_fit_utils_vaistudio:
    git:
      url: https://github.com/s0punk/flutter_fit_utils_vaistudio.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0